import type {Metadata} from "next";
import "./globals.css";
import SideBar from "@/components/sideBar";
import {Poppins} from 'next/font/google'
import ReactQueryProvider from "@/providers/reactQueryProvider";
import EntryWrapper from "@/components/entryWrapper";
import ToastProvider from "@/providers/toastProvider";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const poppins = Poppins({
    weight: ['400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
})

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={poppins.className}>
        <body
        >
        <ReactQueryProvider>
            <ToastProvider>
                <EntryWrapper>
                    <SideBar/>
                    <main className="md:ml-[165px] flex-1 p-4">
                        {children}
                    </main>
                </EntryWrapper>
            </ToastProvider>
        </ReactQueryProvider>
        </body>
        </html>
    );
}
